# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/config-start-tasks/tasks:
  - name: show markdown readme
    # this is a bit of a hack to make sure the VS code server is ready
    command: sleep 3 && open README.md
    openMode: tab-after
    # https://github.com/lpmi-13/merge-a-matic/blob/main/.gitpod.yml
  - init: |
      npm install -g study-lenses
      study --port=3000

